apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component8
    app.kubernetes.io/part-of: test-app
  name: test-component8
  namespace: jvm-bld-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component8
    spec:
      containers:
      - image: quay.io/psturc/test-images@sha256:e8e928c334d960d2fa002a14011fb33247414dc39b6b854a870b5352ab2998a7
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
